---

- name: dependencies are installed (yum)
  yum:
    name: "{{ yum_pkg }}"
    state: present
  loop: "{{ yum_packages_pip }}"
  loop_control:
    loop_var: yum_pkg
  when: ansible_os_family == 'RedHat'

- name: dependencies are installed (apt)
  apt:
    name: "{{ apt_pkg }}"
    state: present
    cache_valid_time: 3600
  loop: "{{ apt_packages_pip }}"
  loop_control:
    loop_var: apt_pkg
  when: ansible_os_family == 'Debian'

- name: set radicale executable
  set_fact:
    radicale_executable: "/usr/local/bin/radicale"

- name: radicale is installed
  pip:
    name: radicale
    version: "{{ radicale_version }}"
    executable: pip3
    extra_args: "{{ '--upgrade' if radicale_version == 'latest' else omit }}"
  notify: restart radicale
