---

- name: dependencies are installed (yum)
  yum:
    name: "{{ item }}"
    state: present
  loop: "{{ yum_packages_pip }}"
  when: ansible_os_family == 'RedHat'

- name: dependencies are installed (apt)
  apt:
    name: "{{ item }}"
    state: present
    cache_valid_time: 3600
  loop: "{{ apt_packages_pip }}"
  when: ansible_os_family == 'Debian'

- name: set radicale executable
  set_fact:
    radicale_executable: "/usr/local/bin/radicale"

- name: radicale is installed
  pip:
    name: radicale
    version: "{{ radicale_version }}"
    executable: pip3
    extra_args: --upgrade
  notify: restart radicale
