---

- name: Combine configuration dict
  set_fact: >
    _radicale_config="{{
      radicale_default_config |
      combine(radicale_config |
      default({}),
      recursive=True)
    }}"

- name: Combine logging dict
  set_fact: >
    _radicale_logging="{{
      radicale_default_logging |
      combine(radicale_logging |
      default({}),
      recursive=True)
    }}"

- name: Include prepare
  import_tasks: prepare.yml
  become: true

- name: "Include install from {{ radicale_install_from }}"
  include_tasks: "install_{{ radicale_install_from }}.yml"

- name: Include configure
  import_tasks: configure.yml
  become: true
